
name: tattoo_holoconnect
description: Aplicación de realidad aumentada para tatuajes personalizados.

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^latest_version
  firebase_auth: ^latest_version
  cloud_firestore: ^latest_version
  firebase_storage: ^latest_version
  qr_flutter: ^latest_version
  ar_flutter_plugin: ^latest_version
  lottie: ^latest_version
  share_plus: ^latest_version
git init
git add .
git commit -m "Código inicial de Tattoo HoloConnect"
git branch -M main
git remote add origin https://github.com/Erasmor4213/TattooHoloConnect.git
git push -u origin main


